actamap/urls.py
from django.contrib import admin
from django.urls import include, path
from mainmap.views import HomePageView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainmap.urls")),
    path("", HomePageView.as_view()),
]

mainmap/urls.py
from django.urls import path

from .views import AboutPage, ContactPage, HomePageView, station_feedback

urlpatterns = [
    path("", HomePageView.as_view(), name="map"),
    path("contact", ContactPage.as_view(), name="contact"),
    path("about", AboutPage.as_view(), name="about"),
    path("stationfeedback/<int:pk>/", station_feedback, name="stationfeedback"),
]

mainmap/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse


class SubwayStation(models.Model):
    station_id = models.IntegerField(validators=[MaxValueValidator(523)], default=-1)
    complex_id = models.IntegerField(null=False, default=-1)
    gtfs_stop_id = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    division = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    line = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    stop_name = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    borough = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    daytime_routes = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    structure = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    gtfs_latitude = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    gtfs_longitude = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    north_direction_label = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    south_direction_label = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    ada = models.IntegerField(validators=[MaxValueValidator(2)], default=-1)
    ada_notes = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    georeference = models.CharField(
        null=False, blank=False, max_length=700, default="No information available"
    )
    lon = models.FloatField(null=False, blank=False, default=-1)
    lat = models.FloatField(null=False, blank=False, default=-1)

    def __str__(self):
        return f"{self.stop_name} -- {self.lat},{self.lon}"

    def get_absolute_url(self):
        return reverse("stationfeedback", kwargs={"pk": self.pk})


class Feedback(models.Model):
    station = models.ForeignKey(SubwayStation, on_delete=models.PROTECT)
    text = models.TextField()

    def __str__(self):
        return f"{self.station} - {self.text}"

mainmap/forms.py
from django import forms

class FeedbackForm(forms.Form):
    station_name = forms.CharField(label="What is the name of the station you'd like to submit feedback about?", max_length=500)
    feedback_text = forms.CharField(label="What advice would you like to give others who use wheelchairs?", widget=forms.Textarea)

mainmap/views.py
import json
import random
from typing import Any, Dict

from django.shortcuts import get_object_or_404, render
from django.views.generic import TemplateView

from .models import Feedback, SubwayStation


class HomePageView(TemplateView):
    """
    The format that this data needs to be in is:

    const clearances = {
        type: 'FeatureCollection',
        features: [
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [-74.07515140286641, 40.581379513893616]
                },
                "properties": {
                    "clearance": "13'2"
                }
            }
        ]
    }
    """

    model = SubwayStation
    template_name = "home.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        # get the subway location that is in the database
        subway_station_locations = SubwayStation.objects.all()

        object_ids = []
        lat_values = []
        lon_values = []
        stop_names = []
        line_names = []
        ada_values = []

        for station in subway_station_locations:
            lat = station.lat
            lon = station.lon
            stop_name = station.stop_name
            line = station.line
            ada = station.ada

            object_ids.append(station.pk)
            lat_values.append(lat)
            lon_values.append(lon)
            stop_names.append(stop_name)
            line_names.append(line)
            ada_values.append(ada)

        context = super().get_context_data(**kwargs)
        context["object_ids"] = object_ids
        context["lat"] = lat_values
        context["lon"] = lon_values
        context["stop_name"] = stop_names
        context["line_name"] = line_names
        context["adas"] = ada_values

        return context

    def clean_descrip(self, descrip):
        descrip = descrip.strip("()")

        return descrip

    def clean_elevators(self, el_str):
        return el_str.strip("()")


# class StationFeedback(DetailView, UpdateView):
#     model = SubwayStation
#     fields = ["community_feedback"]
#     template_name = "station_feedback.html"


def station_feedback(request, pk):
    station = get_object_or_404(SubwayStation, pk=pk)

    if request.method == "POST":
        Feedback.objects.create(station=station, text=request.POST["feedback"])

    return render(request, "station_feedback.html", {"station": station})


class ContactPage(TemplateView):
    template_name = "contact.html"


class AboutPage(TemplateView):
    template_name = "about.html"

mainmap/templates/about.html
{%extends 'base.html'%}

{% block content %}
    <p>Popular consumer maps, like Google Maps, use software to replicate a perfect, error-free world. The real world, of course, is far from perfect. accessibility.nyc makes it easy to crowdsource accessibility data about New York City’s Subways.</p>
    <br>
    <p>The purpose of this map is to help the NYC-based disabled community plan their trips to new places.</p>
{% endblock content%}

mainmap/templates/base.html
{% load static %}
<html lang="en">

<head>
    <title>Community Notes on Subway Accessibility</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>How Accessible is each station?</title>

    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />

    <link rel='stylesheet' href="{% static 'mainmap/css/tailwind-out.css' %}" />
    <script>
    // Javascript to toggle the menu
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById('nav-toggle').onclick = function() {
            document.getElementById("nav-content").classList.toggle("hidden");
        }
    });
    </script>
</head>

<body>
    <nav id="header" class="fixed w-full z-[1500] top-0">
        <div class="w-full md:max-w-4xl mx-auto flex flex-wrap items-center justify-between mt-0 py-3">
            <div class="pl-4">
                <a class="text-gray-900 text-base no-underline hover:no-underline font-extrabold text-xl" href="{% url 'map' %}">
                    Subway Accessibility
                </a>
            </div>
            <div class="block lg:hidden pr-4">
                <button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-900 hover:border-green-500 appearance-none focus:outline-none">
                    <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <title>Menu</title>
                        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
                    </svg>
                </button>
            </div>
            <div class="w-full flex-grow lg:flex lg:items-center hidden lg:block lg:w-auto mt-2 lg:mt-0 bg-gray-100 lg:bg-transparent z-2000" id="nav-content">
                <ul class="list-reset lg:flex justify-end flex-1 items-center">
                    <li class="mr-3">
                        <a class="inline-block py-2 px-4" href="{% url 'map' %}">
                            Map
                        </a>
                    </li>
                    <li class="mr-3">
                        <a class="inline-block hover:text-underline py-2 px-4" href="{% url 'contact' %}">Contact</a>
                    </li>
                    <li class="mr-3">
                        <a class="inline-block hover:text-underline py-2 px-4" href="{% url 'about' %}">About this Project</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container w-full md:max-w-3xl mx-auto pt-20">
        <div class="w-full px-4 md:px-6 text-gray-800 leading-normal">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    
</body>

</html>

mainmap/templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-black">Get in Touch</h2>
    <ul class="list-disc">
        <li><a href="mailto:iscdonis@gmail.com">Email Isaac at iscdonis@gmail.com</a></li>
        <li><a href="https://www.meetup.com/transit-techies-nyc/">Join the Transit Techies Meetup</a></li>
    </ul>

    <br>

    <h2 class="mb-4 text-3xl font-extrabold leading-none tracking-tight text-gray-900 md:text-4xl dark:text-black">Advisory Team</h2>
    <ul class="list-disc">
        <li>Sarah Sachs</li>
        <li>Jessica Murray</li>
        <li>Greg Sadetsky</li>
    </ul>
{% endblock content %}

mainmap/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="-mx-4">
    <h1 class="text-center mb-4">How Accessible is each station?</h1>

    <!-- Main -->
    <main>
        <div id='map' style='height: 500px;'></div>
    </main>

    <!-- Scripts -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>

    <script>
        const ICON_URL = '{% static "images/accessible_icon.jpg" %}';
    </script>

    <script>
        const isMobile = window.navigator.userAgent.match(/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/)

        mapboxgl.accessToken = 'pk.eyJ1IjoiaWNkb25pcyIsImEiOiJjbGZlY3RmYTkwMmxvM3Bxbnp2YnU2aWR2In0.OdqH3NLK3-fyd6UDcI5gbQ';

        // Define boundaries
        var bounds = [[-74.58963551742433, 40.40699857483299],
                     [-73.61177016947053, 41.00965094991757]]
                     
        var map = new mapboxgl.Map({
            container: 'map',
            center: [-73.97231715755181, 40.70811065720056],
            style: 'mapbox://styles/mapbox/streets-v11',
            maxBounds: bounds,
            zoom:8,
            minZoom:5,
            maxZoom: 14
        });
        

        // this counts as loading your data
        const geojson_values = {
          type: 'FeatureCollection',
          features: []
        };

        const object_ids = {{object_ids}}
        const lat_values = {{lat}}
        const lon_values = {{lon}}
        const stop_names = {{stop_name | safe}}
        const line_names = {{line_name | safe}}
        const ada_counts = {{adas}}
        
        let i = 0
        while (i < lat_values.length)
        {
            lat = lat_values[i]
            lon = lon_values[i]
            geojson_values.features.push({
                type: 'Feature',
                geometry: {
                    type: 'Point',
                    coordinates: [lon, lat],
                    color: "rgba(255, 0, 0, 0.5)" // color of the marker with 50% opacity
                },
                properties: {
                    object_id: object_ids[i],
                    station_name: stop_names[i],
                    line_name: line_names[i],
                    ada: ada_counts[i]
                }
            })

            i++
        }

        // Add markers to the map.
        for (const feature of geojson_values.features) {
            // Create a DOM element for each marker.
            const el = document.createElement('div');
            const width = 25;
            const height = 25;
            el.className = 'marker';

            if (feature.properties.ada > 0) {
                el.style.backgroundImage = `url(${ICON_URL})`;
                el.style.width = '20px';
                el.style.height = '20px';
                el.style.backgroundSize = '100%';
            
                // Add markers to the map.
                new mapboxgl.Marker(el).setLngLat(feature.geometry.coordinates).addTo(map);

                el.addEventListener('click', () => {
                    window.location.href = '/stationfeedback/' + feature.properties.object_id;
                });

                if(!isMobile) {
                    let popup = null;
                    // add infowindow on hover
                    el.addEventListener('mouseover', () => {
                        popup = new mapboxgl.Popup({ offset: 25 })
                            .setLngLat(feature.geometry.coordinates)
                            .setHTML(feature.properties.station_name.concat(' - ').concat(feature.properties.line_name))
                            .addTo(map);
                    });
                    // remove infowindow on mouseout
                    el.addEventListener('mouseout', () => {
                        if (popup) {
                            popup.remove();
                        }
                    });
                }
            }
        }

        map.on('load', () => {
            /* Add the data to your map as a layer */
            map.addLayer({
              id: 'locations',
              type: 'circle',
              /* Add a GeoJSON source containing place coordinates and information. */
              source: {
                type: 'geojson',
                data: geojson_values
              },
              paint: {'circle-radius': 2.5}
            });
          });

        var popup = new mapboxgl.Popup({
            closeOnClick: false,
            offset: [0, -15]
          })

        map.on('click', 'locations', (e) => {
            const properties = e.features[0].properties;
            const object_id = properties.object_id;

            window.location.href = '/stationfeedback/' + object_id;
        });

    </script>
</div>
{% endblock content %}

mainmap/templates/station_feedback.html
{% extends "base.html" %}
{% block content %}

<div class="mt-5">
    {% if station.feedback_set.all|length == 0 %}
        <h3>There is no feedback about the {{station.stop_name}} {{station.line}} station yet.</h3>
    {% else %}
        <h3>The community has collected these notes about the {{station.stop_name}} {{station.line}} station:</h3>

        <ul class="list-disc">
            {% for feedback in station.feedback_set.all %}
                <li>{{feedback.text}}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

<h4 class="mt-10"><u>ADA information</u></h4>

<p class="mb-10">There {{station.ada|pluralize:"is,are"}} {{station.ada}} ADA elevator{{station.ada|pluralize}} at this station.</p> <p>{{station.ada_notes}}</p>

<h3><u>Submit your feedback about this station</h3></u>
<br>
<br>
<form action="" method="post">
    {% csrf_token %}
    
    <textarea name="feedback" rows="4" cols="50" class="peer h-500 min-h-[100px] w-full resize-none rounded-[7px] border border-black bg-transparent px-3 py-2.5 font-sans text-sm font-normal text-blue-gray-700 outline outline-0 transition-all placeholder-shown:border placeholder-shown:border-blue-gray-200 placeholder-shown:border-t-blue-gray-200 focus:border-2 focus:border-gray-900 focus:outline-0 disabled:resize-none disabled:border-0 disabled:bg-blue-gray-50" placeholder="Enter your feedback here"></textarea>
    <input type="submit" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" value="Share with community">
</form>
{% endblock content%}

mainmap/templates/thank_you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>How Accessible is each station?</title>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
    <!-- Styles -->


</head>
<body>
<h1>Thank You!</h1>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 style="text-align: center;">How Accessible is each station?</h3>
<p>Click on the links below the map to submit feedback about a station </p>

    <!-- Main -->
    <main>
        <div id='map' style='width: 900px; height: 500px;'></div>
    </main>

    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'stationfeedback' object.pk %}">{{object.stop_name}} {{object.line}}</li>
        {% empty %}
            <li>Something went wrong.</li>
        {% endfor %}
    </ul>

    <!-- Scripts -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>

    <script>

        mapboxgl.accessToken = 'pk.eyJ1IjoiaWNkb25pcyIsImEiOiJjbGZlY3RmYTkwMmxvM3Bxbnp2YnU2aWR2In0.OdqH3NLK3-fyd6UDcI5gbQ';
        var map = new mapboxgl.Map({
            container: 'map',
            center: [-73.93006, 40.69218],
            style: 'mapbox://styles/mapbox/streets-v11',
            zoom: 10
        });

        // this counts as loading your data
        const geojson_values = {
          type: 'FeatureCollection',
          features: []

        };

        const lat_values = {{lat}}
        const lon_values = {{lon}}
        const stop_names = {{stop_name | safe}}
        const line_names = {{line_name | safe}}
        const ada_counts = {{adas}}
        
        let i = 0
        while (i < lat_values.length)
        {
            lat = lat_values[i]
            lon = lon_values[i]
            geojson_values.features.push({
                type: 'Feature',
                geometry: {
                    type: 'Point',
                    coordinates: [lon, lat]
                },
                properties: {
                    station_name: stop_names[i],
                    line_name: line_names[i],
                    ada: ada_counts[i]
                }
            })

            i++
        }

        // Add markers to the map.
        for (const marker of geojson_values.features) {
            // Create a DOM element for each marker.
            const el = document.createElement('div');
            const width = 5;
            const height = 5;
            el.className = 'marker';

            console.log(marker.properties.ada)

            if (marker.properties.ada > 0) {
                el.style.backgroundImage = "url({% static 'images/accessible_icon.jpg' %})";
            }

            el.style.width = '10px';
            el.style.height = '10px';
            el.style.backgroundSize = '100%';
            
            // Add markers to the map.
            new mapboxgl.Marker(el)
            .setLngLat(marker.geometry.coordinates)
            .addTo(map);
            }


        map.on('load', () => {
            /* Add the data to your map as a layer */
            map.addLayer({
              id: 'locations',
              type: 'circle',
              /* Add a GeoJSON source containing place coordinates and information. */
              source: {
                type: 'geojson',
                data: geojson_values
              }
            });
          });

        var popup = new mapboxgl.Popup({
            closeOnClick: false,
            offset: [0, -15]
          })

        map.on('mousemove', 'locations', (e) => {
            const name = e.features[0].properties.station_name;
            const line = e.features[0].properties.line_name;
            const coordinates = e.features[0].geometry.coordinates.slice();

            popup
                .setLngLat(coordinates)
                .setHTML(name.concat(' - ').concat(line))
                .addTo(map);
        });

        map.on('mouseleave', 'locations', (e) => {
            popup.remove();
        });


    </script>
{% endblock content %}